{% set name = "napari-multitask" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-multitask-{{ version }}.tar.gz
  sha256: cb73e75c2a3c398868b2c6a1034cddfc0d87375f7281aa5f686b3e1b3cd36625

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magic-class >=0.5.11
    - napari
    - python >={{ python_min }}

test:
  imports:
    - napari_multitask
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-multitask/
  summary: Multitasking in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - hanjinliu
